sudo: false
language: node_js

node_js:
  - "6.10"

env:
  global:
    # Encrypted: NPM_AUTH_TOKEM=<NPM_AUTH_TOKEM>
    - secure: "OygmYe2WTQIi38OWGyZV0lhljlQ5xqLACBn65/bpKrOKhr+g5cUzJS31UvkoqlaqacTjuyTJnWYGLVXTp5hg1r8EYJFOHqz1Vm0OySkMTmiEeuke9BC24YmQ4oPuwNNszX5as24ZiKZr47cGohboQCpsI3CHspjpbX09BYpvRIjpusEIE8djJGpBuB4q40Uprqzo/GUXHZEV5lbI8JqoNZQvcofLVJ8M+dI2bM2RmLAlE++IX+qoIqtEF52mwROxUFxxQpEvzPUwPhLTFWfSk6lFsgK37XdXZ7x9Pe6UdUFzEFDFp5iIQtvxxPXXsKO4qB/LL5mYC0l6VgKRqtYtcLr2sFBwxjQfmSZZHEhSZcd9QT0HwPNTPidyF1SgsQNLIChe0+1fuRBTwhG5LFy0kkUNXU/Ovh8Pe6Igq4U0jppdfk6uxlDuqdAgDhacZsejpmqkS1J+8aUPgn/ZdAi2t37HOXiPayfU/OfY6GBkkgooBI3DWiOQuuILzWF3hNlPPn6ym9tTZWUsihYrl0l62llkdCsiNY5vN+sl3FWF5BnQOFJoPKT8t4c155F9+tIN1CPK0YLWn/vhhp8X5TRlUyzXmAjjcTEqx0E2+t06EHHB/VMe4uc7hTkaOXLSH31y78XcXdmPuMrMOGMwgZmFsbK/ykamqcaSAUQVS14VAmg="

install:
  - npm install -g gulp-cli
  - npm install || (sleep 10s && npm install)

script:
  - gulp travis
  - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEM" > ~/.npmrc
  - ./deploy.sh

after_script:
  # Cleanup NPM credentials
  - rm -f ~/.npmrc

notifications:
  slack:
    on_success: change
    rooms:
      # Encrypted '<ACCOUNT>:<TOKEN>#<ROOM>'
      - secure: "Urpr0Zm44QtTeLA07yBMEohrP65F4Xn0Ofu06k/zGGEfZ4h0dX3R74Gf4NeKQZiQqhUqqKGDnrZF/lJotgfQgk+vWCRghXaXhkeGWULsKI6M7rMWP0jd/6E0cTtvvAOwgiC/nXz29fE9dvbQPIZSZ26+ToW9UTVHEP9igGdu07Bs06IIupj55axGhGq+TZYQSx3rHm6HQ4Phzqe3LTZMGtcB7EFN/KrVqxIcPtiednkDQhPSp9mqY6m3EVrFikKN8hcPjiHlmWAseAOGitI6enAe/3EvlJviY8OA732UxWVBplbOQ+R9eTI3I2UP5BbyHNZvOp1bPO8cyhutJ7txFgbOj5yJMlqTcrEfsMsKR+rlLozWJYkOM2954IMgGo0IWvuRWfBYOf0miD5izCKYSbbDa35QWc43MMyuPOhrh/Wg8W19VtLRk0qFaxcmg/0SLUcHr445zxVl8FO0Oc29c6dDCxRKHPNAuqnYpFga3QbTALpa2hIi2z+PaUIFGfcaTTSo3ch0GwToFPOnbmIekvcTm030EbK9LATCljLl9yNGbW+hO7VDZiZv2b9UjePerDZOrRatGiHs9F1uGYvwdz7QKSbwRz7hCgmFSGlqDj19HaSs2T9lPhUIo043A74htkTkfDWXc5TNDtMIGKA2TSA4LsmlNusJoMJuKbHWHw0="